### ISSUE TITLE
Page 17 Hello OpenWisk

### ISSUE THREAD

**Issue by echeadle** [PacktPublishing/Docker-for-Serverless-Applications#2]
Then change the directory into devtools/docker-compose, and manually do image
pulling, using the following commands:
1. $ cd devtools/docker-compse
2. $ docker-compose pull
3. $ docker pull openwhisk/nodejs6action
Step 2 fails:
$ docker-compose pull
WARNING: The DOCKER_COMPOSE_HOST variable is not set. Defaulting to a blank string.
ERROR: Couldn't find env file: /home/echeadle/tmp/openwhisk/local.env
[echeadle@serverless docker-compose]$ docker-compose
Define and run multi-container applications with Docker.

**Comment by echeadle** [comment]
These are not issues with the code in the repos. I did not think of that. Is it better to submit questions about the book to the packet website?  Or do you prefer to have questions here in GitHub?

**Comment by gaurav-packt** [comment]
Please reopen the issue if it still exists.
